import React from "react";
import { Box, CssBaseline, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import "./globals.css";
import theme from "../theme/theme";
import Sidebar from "../layout/Sidebar/Sidebar";
import Header from "../layout/Header/Header";
import Footer from "../layout/Footer/Footer";

export const metadata = {
  title: "Best Musics",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{ key: "mui" }}>
          <ThemeProvider theme={theme}>
            <Box
              sx={{
                display: "flex",
                justifyContent: "space-between",
              }}
            >
              <Sidebar />
              <CssBaseline>
                <Box
                  sx={{
                    maxWidth: "1231px",
                    width: "100%",
                    margin: "0 auto",
                    height: "100vh",
                  }}
                >
                  <Header />
                  {children}
                  <Footer />
                </Box>
              </CssBaseline>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
