import React from "react";
import { Box, CssBaseline, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import "./globals.css";
import theme from "../theme/theme";
import Sidebar from "../layout/Sidebar/Sidebar";

export const metadata = {
  title: "Best Musics",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{ key: "mui" }}>
          <ThemeProvider theme={theme}>
            <Box
              sx={{
                display: "flex",
                gap: "25px",
              }}
            >
              <Sidebar />
              <CssBaseline>{children}</CssBaseline>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
